# @package _global_

# global parameters
device: cuda
debug: False
deterministic: False
num_workers: -1
seed: 0
comment: ""
task: ""
track_inference_time: False
limit_samples: False

# network
net:
  type: ""
  num_hidden: -1
  num_blocks: -1
  readout_pool: "mean"
  readout_head: True
  dropout: 0.0
  dropout_type: Dropout
  norm: ""
  nonlinearity: ""
  pooling_layers: !!python/tuple [-1]
  width_factors: !!python/tuple [0.0]
  block:
    type: default
    prenorm: True
    use_bias: True
    layer_scale_init_value: 0.0
    bottleneck_factor: -1
    drop_path: 0.0
  kernel:
    type: ""
    isotropic: False
    num_hidden: -1
    num_layers: -1
    omega_0: 0.0
    input_scale: 0.0
    use_bias: True
    size: -1
    norm: Identity
    nonlinearity: Identity
    sigma: 0.0
# gridifier
gridifier:
  connectivity: ""
  grid_resolution: -1
  circular_grid: False
  num_neighbors: -1
  num_backward_neighbors: -1
  segmentation_backward_edges: False
  same_k_forward_backward: True
  reuse_edges: True
  conditioning: ""
  aggregation: ""
  use_pos_in_output: False
  position_embed:
    type: ""
    num_hidden: -1
    num_layers: -1
    omega_0: 0.0
    input_scale: 0.0
    use_bias: True
    size: -1
    norm: Identity
    nonlinearity: Identity
  update_net:
    type: ""
    num_hidden: -1
    num_layers: -1
    omega_0: 0.0
    input_scale: 0.0
    use_bias: True
    size: -1
    norm: Identity
    nonlinearity: Identity
  node_embedding:
    type: ""
    num_hidden: -1
    num_layers: -1
    omega_0: 0.0
    input_scale: 0.0
    use_bias: True
    size: -1
    norm: Identity
    nonlinearity: Identity
  message_net:
    type: ""
    num_hidden: -1
    num_layers: -1
    omega_0: 0.0
    input_scale: 0.0
    use_bias: True
    size: -1
    norm: Identity
    nonlinearity: Identity


pointnet:
  connectivity: ""
  num_neighbors: -1
  radius: 0.0
# datamodules
dataset:
  name: ""
  data_dir: "data"
  augment: False
  params:
    num_classes: -1
    use_positions: False
    use_normals: False
    val_split_as_test_split: False
    num_samples: -1
    balance_data: False
    predict: ""
  qm9:
    use_cormorant: False
  md17:
    embed_features: False
    add_edges: False

# training
train:
  do: True
  mixed_precision: False
  epochs: -1
  batch_size: -1
  grad_clip: 0.0
  label_smoothing: 0.0
  max_epochs_no_improvement: 100
  track_grad_norm: -1 # -1 for no tracking.
  accumulate_grad_steps: 1 # Accumulate gradient over different batches.
  distributed: False
optimizer:
  type: ""
  lr: 0.0
  mask_lr_ratio: 1.
  momentum: -1.
  nesterov: False
  weight_decay: 0.0
scheduler:
  type: ""
  decay_steps: -1
  factor: 1.0
  patience: -1
  warmup_epochs: -1
  mode: "max"
# testing
test:
  batch_size_multiplier: 1
  before_train: False
# wandb logging
wandb:
  project: dense_point_clouds
  entity: ck-experimental
# checkpoint
pretrained:
  load: False
  alias: "best" #Either best or last
  filename: ""
# hooks; function: application
hooks_enabled: False

